### ISSUE TITLE
how to use in android ? 

### ISSUE THREAD

**Issue by WestbrookZero** [MaybeShewill-CV/MNN-LaneNet#1]

**Comment by MaybeShewill-CV** [comment]
@WestbrookZero Check MNN related files:)

**Comment by 850977164** [comment]
How to compile own MNNConverter tools

**Comment by MaybeShewill-CV** [comment]
@850977164 You'd better check mnn related files or raise an issue there:)

**Comment by 850977164** [comment]
I failed to pass this command in your project,
  bash checkpoint/convert_ckpt_into_mnn_model.sh MNNConverter_TOOL_PATH
I changed the directory to the one you specified in your example, I still failed
Lanenet_model.mnn was not generated in the./checkpoint directory

**Comment by 850977164** [comment]
![企业微信截图_15790775084943](https://user-images.githubusercontent.com/39330916/72418403-ba27cc00-37b5-11ea-803e-2d52197b0f89.png)
@MaybeShewill-CV please take a look

**Comment by MaybeShewill-CV** [comment]
@850977164 I use c++ version converter tools instead of python tool:)

**Comment by 850977164** [comment]
Can you elaborate on that

**Comment by 850977164** [comment]
Which version of protoc are you using

**Comment by MaybeShewill-CV** [comment]
@850977164 Try MNN 0.2.1.0

**Comment by 850977164** [comment]
@MaybeShewill-CV 
This problem occurred while I was executing this command ， what's the reason
cmake .. -DMNN_BUILD_CONVERTER=true && make -j4
![image](https://user-images.githubusercontent.com/39330916/72495770-91a9db80-3862-11ea-951a-4d80ac32d651.png)

**Comment by 850977164** [comment]
@MaybeShewill-CV 
Hello, I have encountered this problem in MNN0.2.1 implementation
![image](https://user-images.githubusercontent.com/39330916/72503411-9d9f9880-3876-11ea-8341-69b734a9041c.png)

**Comment by MaybeShewill-CV** [comment]
@850977164 测试过了 mnn 0.2.1.0没有这个问题 你遇到的这个问题可以去mnn的项目下提issue:)
