### ISSUE TITLE
Convert  MNN Model error

### ISSUE THREAD

**Issue by zhwis** [MaybeShewill-CV/MNN-LaneNet#2]
python ./tools/freeze_lanenet_model.py it can output tusimple_lanenet.pb, I can parse this model file, and visualize well. but convert mnn model err:
==== output_shape is not consistent with inferred output shape in MNN. ====
====(height,width): (32,64) vs (1024,1024)
 ====Converte Tensorflow's Op lanenet_model/vgg_frontend/vgg16_decode_module/binary_seg_decode/decode_stage_4_fuse/deconv/deconv/conv2d_transpose , type = Conv2DBackpropInput, failed, may be some node is not const
==== output_shape is not consistent with inferred output shape in MNN. ====
====(height,width): (32,64) vs (1024,1024)
 ====Converte Tensorflow's Op lanenet_model/vgg_frontend/vgg16_decode_module/binary_seg_decode/decode_stage_4_fuse/deconv/deconv/conv2d_transpose , type = Conv2DBackpropInput, failed, may be some node is not const
==== output_shape is not consistent with inferred output shape in MNN. ====
====(height,width): (32,64) vs (1024,1024)
 ====Converte Tensorflow's Op lanenet_model/vgg_frontend/vgg16_decode_module/binary_seg_decode/decode_stage_4_fuse/deconv/deconv/conv2d_transpose , type = Conv2DBackpropInput, failed, may be some node is not const
1=1 in onComputeInfo, 389 
How should i do, thx !

**Comment by MaybeShewill-CV** [comment]
@zhwis Test MNN 0.2.1.0

**Comment by zhwis** [comment]
It‘s work. thx

**Comment by 850977164** [comment]
@zhwis How did you ultimately execute

**Comment by 850977164** [comment]
您好，利用MNN执行之后总容量大于嵌入式主板内存，应该怎么解决这个问题呢？
谢谢

**Comment by MaybeShewill-CV** [comment]
@850977164 这个可能得咨询一下mnn的开发者
