### ISSUE TITLE
cmake c++11 issue

### ISSUE THREAD

**Issue by kaishijeng** [MaybeShewill-CV/MNN-LaneNet#3]
When I make build, I got the following issue:

lanenet_model.cpp:427:10: error: ‘iota’ is not a member of ‘std’
     std::iota(indexes.begin(), indexes.end(), 0);
          ^~~~

My g++ version: g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

CMakefile has set CPP_11 flag on

Do you know how to fix this?

Thanks

**Comment by MaybeShewill-CV** [comment]
@kaishijeng Maybe you can google how to fix this. Besides my gcc version 5.4.0.:)

**Comment by kaishijeng** [comment]
OK, I fixed it.
Do you know where I can find config.ini to run?

Thanks,

**Comment by MaybeShewill-CV** [comment]
@kaishijeng https://github.com/MaybeShewill-CV/MNN-LaneNet/blob/master/build/config.ini You may find it here:)

**Comment by kaishijeng** [comment]
It works and thanks for the helps.

**Comment by MaybeShewill-CV** [comment]
@kaishijeng Welcome:)

**Comment by JunjieLiuSWU** [comment]
> OK, I fixed it.
> Do you know where I can find config.ini to run?
> 
> Thanks,

Hello, I have the same problem, how did you solve it?
