### ISSUE TITLE
为什么在visualize_instance_segmentation_result中color_map有7类，而最后结果只显示0、1、2三类

### ISSUE THREAD

**Issue by q1vs5k5** [MaybeShewill-CV/MNN-LaneNet#4]
非常感谢您的开源项目，谢谢。从中学到很多，在看代码的过程中有点疑问，就是为什么在visualize_instance_segmentation_result中color_map有7类，而最后结果只显示0、1、2三类？

**Comment by MaybeShewill-CV** [comment]
@Royzon 你看错代码了吧 color map中一共有八种颜色是表示图像中最多只能显示八条不同车道线的颜色 最后的结果是聚类出了几条车道线就显示几条车道线 不是只显示0, 1, 2三类。

**Comment by q1vs5k5** [comment]
哦哦哦 明白了,实在是感谢您~
