### ISSUE TITLE
Lanenet with VULKAN support

### ISSUE THREAD

**Issue by naserpiltan** [MaybeShewill-CV/MNN-LaneNet#5]
@MaybeShewill-CV Hi.
I am planning to use MNN-LaneNet with VULKAN backend. Is it possible to make this repo with VULKAN backend ? I read cmakelists.txt but there is no any thing about vulkan backend.
I built MNN project and used libMNN.so in my MNN_LaneNet project but MNN_LaneNet is slower when i use VULKAN backend.

with mnn_config.type = MNN_FORWARD_CPU result :

detect, 211, cost time: 0.246000 ms
detect, 146, cost time: 0.838000 ms
detect, 153, cost time: 872.728027 ms
detect, 204, cost time: 29.430002 ms

with mnn_config.type = MNN_FORWARD_VULKAN result :

Vulkan don't support 2, ArgMax: lanenet_model/vgg_backend/binary_seg/ArgMax
Vulkan don't support 9, Cast: lanenet/Cast
detect, 146, cost time: 0.755000 ms
detect, 153, cost time: 2487.019043 ms
detect, 204, cost time: 31.821001 ms

**Comment by MaybeShewill-CV** [comment]
@naserpiltan You'd better raise an issue in MNN project where you may get a more satisfied answer. Actually I'm not a engineer major in Ai frameworks:)
