### ISSUE TITLE
为什么在安卓上只能运行模型的部分，导致无法获取最终结果

### ISSUE THREAD

**Issue by ymmshi** [MaybeShewill-CV/MNN-LaneNet#7]
你好，首先感谢你的工作。按照你的说明，我成功在linux上跑通了模型，当我想移植到安卓上发现始终无法获得最终结果，在调试的过程中发现以下情况：

在linux上运行 _m_lanenet_model->runSessionWithCallBack(_m_lanenet_session, beforeCallBack, AfterCallBack, true);
可以获取到所有op的name，

`
LaneNet_1/bisenetv2_frontend/detail_branch/stage_1/conv_block_1_repeat_1/3x3_conv/conv/Conv2D
LaneNet_1/bisenetv2_frontend/detail_branch/stage_1/conv_block_2_repeat_1/3x3_conv/conv/Conv2D
LaneNet_1/bisenetv2_frontend/detail_branch/stage_2/conv_block_1_repeat_1/3x3_conv/conv/Conv2D
LaneNet_1/bisenetv2_frontend/detail_branch/stage_2/conv_block_2_repeat_1/3x3_conv/conv/Conv2D
LaneNet_1/bisenetv2_frontend/detail_branch/stage_2/conv_block_2_repeat_2/3x3_conv/conv/Conv2D
LaneNet_1/bisenetv2_frontend/detail_branch/stage_3/conv_block_1_repeat_1/3x3_conv/conv/Conv2D
LaneNet_1/bisenetv2_frontend/detail_branch/stage_3/conv_block_2_repeat_1/3x3_conv/conv/Conv2D
LaneNet_1/bisenetv2_frontend/detail_branch/stage_3/conv_block_2_repeat_2/3x3_conv/conv/Conv2D
LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/detail_branch/3x3_dw_conv_block/depthwise_conv_output
LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/detail_branch/1x1_conv_block/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_1/se_block_1_repeat_1/stem_block/conv_block_1/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_1/se_block_1_repeat_1/stem_block/downsample_branch_left/1x1_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_1/se_block_1_repeat_1/stem_block/downsample_branch_left/3x3_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_1/se_block_1_repeat_1/stem_block/downsample_branch_right/maxpooling_block
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_1/se_block_1_repeat_1/stem_block/concate_features
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_1/se_block_1_repeat_1/stem_block/final_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/input_project_dw_conv_block/depthwise_conv_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/input_project_1x1_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/3x3_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/depthwise_conv_block_1/depthwise_conv_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/depthwise_conv_block_2/depthwise_conv_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/1x1_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/fused_features
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/ge_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/3x3_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/depthwise_conv_block/depthwise_conv_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/1x1_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/ge_output___tr4LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/fused_features
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/1x1_conv_block/bn/FusedBatchNorm___tr4LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/fused_features
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/fused_features
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/ge_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/ge_output___tr4LaneNet_1/bisenetv2_frontend/semantic_branch/stage_4/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/input_project_dw_conv_block/depthwise_conv_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_4/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/input_project_dw_conv_block/depthwise_conv_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_4/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/input_project_1x1_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/ge_output___tr4LaneNet_1/bisenetv2_frontend/semantic_branch/stage_4/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/3x3_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_4/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/3x3_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_4/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/depthwise_conv_block_1/depthwise_conv_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_4/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/depthwise_conv_block_2/depthwise_conv_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_4/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/1x1_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_4/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/fused_features
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_4/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/ge_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_4/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/3x3_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_4/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/depthwise_conv_block/depthwise_conv_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_4/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/1x1_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_4/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/ge_output___tr4LaneNet_1/bisenetv2_frontend/semantic_branch/stage_4/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/fused_features
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_4/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/1x1_conv_block/bn/FusedBatchNorm___tr4LaneNet_1/bisenetv2_frontend/semantic_branch/stage_4/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/fused_features
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_4/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/fused_features
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_4/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/ge_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_4/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/ge_output___tr4LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/input_project_dw_conv_block/depthwise_conv_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/input_project_dw_conv_block/depthwise_conv_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/input_project_1x1_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_4/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/ge_output___tr4LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/3x3_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/3x3_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/depthwise_conv_block_1/depthwise_conv_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/depthwise_conv_block_2/depthwise_conv_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/1x1_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/fused_features
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/ge_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/3x3_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/depthwise_conv_block/depthwise_conv_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/1x1_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/ge_output___tr4LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/fused_features
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/1x1_conv_block/bn/FusedBatchNorm___tr4LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/fused_features
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/fused_features
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/ge_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/ge_output___tr4LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_2/gather_expansion_block/stride_equal_one_module/3x3_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_2/gather_expansion_block/stride_equal_one_module/3x3_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_2/gather_expansion_block/stride_equal_one_module/depthwise_conv_block/depthwise_conv_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_2/gather_expansion_block/stride_equal_one_module/1x1_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_2/gather_expansion_block/stride_equal_one_module/1x1_conv_block/bn/FusedBatchNorm___tr4LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_2/gather_expansion_block/stride_equal_one_module/fused_features
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_2/gather_expansion_block/stride_equal_one_module/fused_features
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_2/gather_expansion_block/stride_equal_one_module/ge_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_2/gather_expansion_block/stride_equal_one_module/ge_output___tr4LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_3/gather_expansion_block/stride_equal_one_module/3x3_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_3/gather_expansion_block/stride_equal_one_module/3x3_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_3/gather_expansion_block/stride_equal_one_module/depthwise_conv_block/depthwise_conv_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_3/gather_expansion_block/stride_equal_one_module/1x1_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_3/gather_expansion_block/stride_equal_one_module/1x1_conv_block/bn/FusedBatchNorm___tr4LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_3/gather_expansion_block/stride_equal_one_module/fused_features
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_3/gather_expansion_block/stride_equal_one_module/fused_features
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ge_block_2_repeat_3/gather_expansion_block/stride_equal_one_module/ge_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ce_block_3_repeat_1/context_embedding_block/global_avg_pooling
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ce_block_3_repeat_1/context_embedding_block/global_avg_pooling___tr4LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ce_block_3_repeat_1/context_embedding_block/bn/FusedBatchNorm
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ce_block_3_repeat_1/context_embedding_block/bn/FusedBatchNorm
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ce_block_3_repeat_1/context_embedding_block/conv_block_1/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ce_block_3_repeat_1/context_embedding_block/conv_block_1/relu___tr4LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ce_block_3_repeat_1/context_embedding_block/fused_features
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ce_block_3_repeat_1/context_embedding_block/fused_features
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ce_block_3_repeat_1/context_embedding_block/fused_features___tr4LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ce_block_3_repeat_1/context_embedding_block/final_conv_block/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_5/ce_block_3_repeat_1/context_embedding_block/final_conv_block/Conv2D
LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/semantic_branch/3x3_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/semantic_branch/semantic_upsample_features
LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/semantic_branch/semantic_upsample_sigmoid
LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/detail_branch/1x1_conv_block/Conv2D___tr4LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/aggregation_features/guided_detail_features
LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/semantic_branch/semantic_upsample_sigmoid___tr4LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/aggregation_features/guided_detail_features
LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/aggregation_features/guided_detail_features
LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/detail_branch/3x3_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/detail_branch/avg_pooling_block
LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/semantic_branch/3x3_dw_conv_block/depthwise_conv_output
LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/semantic_branch/1x1_conv_block/Conv2D
LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/semantic_branch/semantic_remain_sigmoid
LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/detail_branch/avg_pooling_block___tr4LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/aggregation_features/guided_semantic_features
LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/semantic_branch/semantic_remain_sigmoid___tr4LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/aggregation_features/guided_semantic_features
LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/aggregation_features/guided_semantic_features
LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/aggregation_features/guided_semantic_features___tr4LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/aggregation_features/guided_upsample_features
LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/aggregation_features/guided_upsample_features
LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/aggregation_features/guided_upsample_features___tr4LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/aggregation_features/fused_features
LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/aggregation_features/fused_features
LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/aggregation_features/fused_features___tr4LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/aggregation_features/aggregation_feature_output/conv/Conv2D
LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/aggregation_features/aggregation_feature_output/conv/Conv2D
LaneNet_1/bisenetv2_frontend/binary_segmentation_branch/conv_3x3/conv/Conv2D
LaneNet_1/bisenetv2_frontend/binary_segmentation_branch/conv_1x1/conv/Conv2D
LaneNet_1/bisenetv2_frontend/binary_segmentation_branch/final_conv/conv/Conv2D
LaneNet_1/bisenetv2_frontend/binary_segmentation_branch/binary_logits
LaneNet_1/bisenetv2_frontend/binary_segmentation_branch/binary_logits___tr4LaneNet_1/bisenetv2_backend/binary_seg/Softmax
LaneNet_1/bisenetv2_backend/binary_seg/Softmax
LaneNet_1/bisenetv2_backend/binary_seg/ArgMax
lanenet/Cast
lanenet/final_binary_output
LaneNet_1/bisenetv2_frontend/instance_segmentation_branch/conv_3x3/conv/Conv2D
LaneNet_1/bisenetv2_frontend/instance_segmentation_branch/conv_1x1/conv/Conv2D
LaneNet_1/bisenetv2_frontend/instance_segmentation_branch/instance_logits
LaneNet_1/bisenetv2_backend/instance_seg/pix_bn/FusedBatchNorm
LaneNet_1/bisenetv2_backend/instance_seg/pix_relu
LaneNet_1/bisenetv2_backend/instance_seg/pix_embedding_conv/Conv2D
LaneNet_1/bisenetv2_backend/instance_seg/pix_embedding_conv/Conv2D___tr4lanenet/final_pixel_embedding_output
lanenet/final_pixel_embedding_output
`

但是，在安卓上运行runSessionWithCallBack（）时，只能打印前26个tensor name，说明后面都没有运行，请问这是什么情况？

`
LaneNet_1/bisenetv2_frontend/detail_branch/stage_1/conv_block_1_repeat_1/3x3_conv/conv/Conv2D
LaneNet_1/bisenetv2_frontend/detail_branch/stage_1/conv_block_2_repeat_1/3x3_conv/conv/Conv2D
LaneNet_1/bisenetv2_frontend/detail_branch/stage_2/conv_block_1_repeat_1/3x3_conv/conv/Conv2D
LaneNet_1/bisenetv2_frontend/detail_branch/stage_2/conv_block_2_repeat_1/3x3_conv/conv/Conv2D
LaneNet_1/bisenetv2_frontend/detail_branch/stage_2/conv_block_2_repeat_2/3x3_conv/conv/Conv2D
LaneNet_1/bisenetv2_frontend/detail_branch/stage_3/conv_block_1_repeat_1/3x3_conv/conv/Conv2D
LaneNet_1/bisenetv2_frontend/detail_branch/stage_3/conv_block_2_repeat_1/3x3_conv/conv/Conv2D
LaneNet_1/bisenetv2_frontend/detail_branch/stage_3/conv_block_2_repeat_2/3x3_conv/conv/Conv2D
LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/detail_branch/3x3_dw_conv_block/depthwise_conv_output
LaneNet_1/bisenetv2_frontend/aggregation_branch/guided_aggregation_block/detail_branch/1x1_conv_block/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_1/se_block_1_repeat_1/stem_block/conv_block_1/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_1/se_block_1_repeat_1/stem_block/downsample_branch_left/1x1_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_1/se_block_1_repeat_1/stem_block/downsample_branch_left/3x3_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_1/se_block_1_repeat_1/stem_block/downsample_branch_right/maxpooling_block
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_1/se_block_1_repeat_1/stem_block/concate_features
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_1/se_block_1_repeat_1/stem_block/final_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/input_project_dw_conv_block/depthwise_conv_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/input_project_1x1_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/3x3_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/depthwise_conv_block_1/depthwise_conv_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/depthwise_conv_block_2/depthwise_conv_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/1x1_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/fused_features
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_1_repeat_1/gather_expansion_block/stride_equal_two_module/ge_output
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/3x3_conv_block/conv/Conv2D
LaneNet_1/bisenetv2_frontend/semantic_branch/stage_3/ge_block_2_repeat_1/gather_expansion_block/stride_equal_one_module/depthwise_conv_block/depthwise_conv_output
`

**Comment by MaybeShewill-CV** [comment]
@ymmshi 抱歉 我不懂安卓开发 这个问题 可能你还是得咨询mnn的相关开发人员:)

**Comment by ymmshi** [comment]
> @ymmshi 抱歉 我不懂安卓开发 这个问题 可能你还是得咨询mnn的相关开发人员:)

好的，还是感谢您！
